### ISSUE TITLE
Errors before first read are uncaught promises in this polyfill, but not in Chrome

### ISSUE THREAD

**Issue by pimterry** [creatorrr/web-streams-polyfill#14]
(I'm opening this here because it's the most obvious place, but it's not 100% clear where the fault lies, I'd be interested to discuss)

Example:

```js
// const ReadableStream = require('web-streams-polyfill').ReadableStream;

let stream = new ReadableStream({
    start(controller) {
        controller.error(new Error('Error on startup'));
    }
});

let reader = stream.getReader();
```

Running this in Chrome 67, with native ReadableStream support, prints nothing. A rejected promise is then returned from any subsequent `reader.read()` calls.

Running the same in node 8.11.1 with this polyfill (uncommenting the first line) prints:

```
(node:5309) UnhandledPromiseRejectionWarning: Error: Error on startup
    at Object.start (.../test-whatwg.js:5:26)
    at exports.InvokeOrNoop (.../node_modules/web-streams-polyfill/dist/polyfill.js:1283:17)
    at new ReadableStreamDefaultController (.../node_modules/web-streams-polyfill/dist/polyfill.js:2349:23)
    at new ReadableStream (.../node_modules/web-streams-polyfill/dist/polyfill.js:1461:40)
    at Object.<anonymous> (.../test-whatwg.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
(node:5309) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5309) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This seems to be caused by `_closedPromise` created in `ReadableStreamReaderGenericInitialize`. This promise is created during the `getReader()` call, and then rejected when any errors occur, but no handlers are attached until much later.

As far as I can tell the latter unhandled promise behaviour seems to follow the spec, so perhaps this should be a Chrome bug. I'm not sure how to test the reference implementation to confirm - perhaps there's a details I'm missing in the spec that means it works nicely there, or perhaps this should really be a spec bug. 

Either way, personally it ends up being very unexpected and awkward behaviour: it rejects a promise and expects downstream code to catch the error, before the promise has ever been exposed. Any idea where the fault lies?

**Comment by pimterry** [comment]
Eugh, sorry, this is my mistake.

I've been using https://github.com/gwicke/node-web-streams, which depends on an [outdated git branch](https://github.com/gwicke/node-web-streams/blob/master/package.json#L28) on this repo. I've updated to 1.3.2 and this now works as expected. Never mind! Sorry for this noise.
